<?php

declare(strict_types=1);

namespace Mt2Cms\Http;

use FastRoute\RouteCollector;
use Mt2Cms\Http\Controller\AdminAccountsController;
use Mt2Cms\Http\Controller\AdminAuthController;
use Mt2Cms\Http\Controller\AdminAwardsController;
use Mt2Cms\Http\Controller\AdminCharactersController;
use Mt2Cms\Http\Controller\AdminDashboardController;
use Mt2Cms\Http\Controller\AdminDropsController;
use Mt2Cms\Http\Controller\AdminGameProtoController;
use Mt2Cms\Http\Controller\AdminGmsController;
use Mt2Cms\Http\Controller\AdminGuildsController;
use Mt2Cms\Http\Controller\AdminItemShopCategoriesController;
use Mt2Cms\Http\Controller\AdminItemShopOrdersController;
use Mt2Cms\Http\Controller\AdminItemShopProductsController;
use Mt2Cms\Http\Controller\AdminLogsController;
use Mt2Cms\Http\Controller\AdminNewsCommentsController;
use Mt2Cms\Http\Controller\AdminNewsPostsController;
use Mt2Cms\Http\Controller\AdminNewsSettingsController;
use Mt2Cms\Http\Controller\AdminRefineController;
use Mt2Cms\Http\Controller\AdminSettingsController;
use Mt2Cms\Http\Controller\AdminShopsController;
use Mt2Cms\Http\Controller\AdminTicketsController;

final class AdminRoutes
{
    public static function register(RouteCollector $r): void
    {
        $r->addRoute('GET', '/admin/login', [AdminAuthController::class, 'showLogin']);
        $r->addRoute('POST', '/admin/login', [AdminAuthController::class, 'login']);
        $r->addRoute('POST', '/admin/logout', [AdminAuthController::class, 'logout']);
        $r->addRoute('GET', '/admin', [AdminDashboardController::class, 'index']);
        $r->addRoute('GET', '/admin/registration', [AdminSettingsController::class, 'registration']);
        $r->addRoute('POST', '/admin/registration', [AdminSettingsController::class, 'saveRegistration']);
        $r->addRoute('GET', '/admin/themes', [AdminSettingsController::class, 'themes']);
        $r->addRoute('POST', '/admin/themes', [AdminSettingsController::class, 'saveThemes']);
        $r->addRoute('GET', '/admin/locale', [AdminSettingsController::class, 'locale']);
        $r->addRoute('POST', '/admin/locale', [AdminSettingsController::class, 'saveLocale']);
        $r->addRoute('GET', '/admin/accounts', [AdminAccountsController::class, 'index']);
        $r->addRoute('GET', '/admin/accounts/new', [AdminAccountsController::class, 'create']);
        $r->addRoute('POST', '/admin/accounts', [AdminAccountsController::class, 'store']);
        $r->addRoute('GET', '/admin/accounts/{id:\d+}', [AdminAccountsController::class, 'edit']);
        $r->addRoute('POST', '/admin/accounts/{id:\d+}', [AdminAccountsController::class, 'update']);
        $r->addRoute('POST', '/admin/accounts/{id:\d+}/block', [AdminAccountsController::class, 'block']);
        $r->addRoute('POST', '/admin/accounts/{id:\d+}/unblock', [AdminAccountsController::class, 'unblock']);
        $r->addRoute('POST', '/admin/accounts/{id:\d+}/delete', [AdminAccountsController::class, 'destroy']);
        $r->addRoute('POST', '/admin/accounts/mass', [AdminAccountsController::class, 'mass']);
        $r->addRoute('GET', '/admin/characters', [AdminCharactersController::class, 'index']);
        $r->addRoute('GET', '/admin/characters/{id:\d+}', [AdminCharactersController::class, 'show']);
        $r->addRoute('GET', '/admin/owned-items/{id:\d+}', [AdminCharactersController::class, 'showOwnedItem']);
        $r->addRoute('GET', '/admin/guilds', [AdminGuildsController::class, 'index']);
        $r->addRoute('GET', '/admin/guilds/{id:\d+}', [AdminGuildsController::class, 'show']);
        $r->addRoute('POST', '/admin/guilds/{id:\d+}', [AdminGuildsController::class, 'update']);
        $r->addRoute('POST', '/admin/guilds/{id:\d+}/kick', [AdminGuildsController::class, 'kick']);
        $r->addRoute('POST', '/admin/guilds/{id:\d+}/comment/{commentId:\d+}/delete', [AdminGuildsController::class, 'deleteComment']);
        $r->addRoute('POST', '/admin/guilds/{id:\d+}/dissolve', [AdminGuildsController::class, 'dissolve']);
        $r->addRoute('GET', '/admin/awards', [AdminAwardsController::class, 'index']);
        $r->addRoute('GET', '/admin/awards/new', [AdminAwardsController::class, 'create']);
        $r->addRoute('POST', '/admin/awards', [AdminAwardsController::class, 'store']);
        $r->addRoute('POST', '/admin/awards/{id:\d+}/delete', [AdminAwardsController::class, 'destroy']);
        $r->addRoute('POST', '/admin/awards/mass', [AdminAwardsController::class, 'mass']);
        $r->addRoute('GET', '/admin/news', [AdminNewsPostsController::class, 'index']);
        $r->addRoute('GET', '/admin/news/new', [AdminNewsPostsController::class, 'create']);
        $r->addRoute('POST', '/admin/news', [AdminNewsPostsController::class, 'store']);
        $r->addRoute('POST', '/admin/news/upload', [AdminNewsPostsController::class, 'upload']);
        $r->addRoute('GET', '/admin/news/comments', [AdminNewsCommentsController::class, 'comments']);
        $r->addRoute('POST', '/admin/news/comments/{id:\d+}/approve', [AdminNewsCommentsController::class, 'approveComment']);
        $r->addRoute('POST', '/admin/news/comments/{id:\d+}/reject', [AdminNewsCommentsController::class, 'rejectComment']);
        $r->addRoute('POST', '/admin/news/comments/{id:\d+}/delete', [AdminNewsCommentsController::class, 'deleteComment']);
        $r->addRoute('GET', '/admin/news/settings', [AdminNewsSettingsController::class, 'settings']);
        $r->addRoute('POST', '/admin/news/settings', [AdminNewsSettingsController::class, 'saveSettings']);
        $r->addRoute('GET', '/admin/news/{id:\d+}', [AdminNewsPostsController::class, 'edit']);
        $r->addRoute('POST', '/admin/news/{id:\d+}', [AdminNewsPostsController::class, 'update']);
        $r->addRoute('POST', '/admin/news/{id:\d+}/delete', [AdminNewsPostsController::class, 'destroy']);
        $r->addRoute('POST', '/admin/news/mass', [AdminNewsPostsController::class, 'mass']);
        $r->addRoute('POST', '/admin/news/comments/mass', [AdminNewsCommentsController::class, 'massComments']);
        $r->addRoute('GET', '/admin/tickets', [AdminTicketsController::class, 'index']);
        $r->addRoute('POST', '/admin/tickets/mass', [AdminTicketsController::class, 'mass']);
        $r->addRoute('GET', '/admin/tickets/{id:\d+}', [AdminTicketsController::class, 'show']);
        $r->addRoute('GET', '/admin/tickets/{id:\d+}/attachments/{attachmentId:\d+}', [AdminTicketsController::class, 'downloadAttachment']);
        $r->addRoute('POST', '/admin/tickets/{id:\d+}/reply', [AdminTicketsController::class, 'reply']);
        $r->addRoute('POST', '/admin/tickets/{id:\d+}/close', [AdminTicketsController::class, 'close']);
        $r->addRoute('POST', '/admin/tickets/{id:\d+}/reopen', [AdminTicketsController::class, 'reopen']);
        $r->addRoute('GET', '/admin/item-shop/categories', [AdminItemShopCategoriesController::class, 'categoriesIndex']);
        $r->addRoute('GET', '/admin/item-shop/categories/new', [AdminItemShopCategoriesController::class, 'categoriesCreate']);
        $r->addRoute('POST', '/admin/item-shop/categories', [AdminItemShopCategoriesController::class, 'categoriesStore']);
        $r->addRoute('POST', '/admin/item-shop/categories/move', [AdminItemShopCategoriesController::class, 'categoriesMove']);
        $r->addRoute('GET', '/admin/item-shop/categories/{id:\d+}/item-search', [AdminItemShopCategoriesController::class, 'categoriesItemSearch']);
        $r->addRoute('POST', '/admin/item-shop/categories/{id:\d+}/products', [AdminItemShopCategoriesController::class, 'categoriesAddProducts']);
        $r->addRoute('POST', '/admin/item-shop/categories/{id:\d+}/products/{productId:\d+}', [AdminItemShopCategoriesController::class, 'categoriesUpdateProduct']);
        $r->addRoute('POST', '/admin/item-shop/categories/{id:\d+}/products/{productId:\d+}/delete', [AdminItemShopCategoriesController::class, 'categoriesRemoveProduct']);
        $r->addRoute('GET', '/admin/item-shop/categories/{id:\d+}', [AdminItemShopCategoriesController::class, 'categoriesEdit']);
        $r->addRoute('POST', '/admin/item-shop/categories/{id:\d+}', [AdminItemShopCategoriesController::class, 'categoriesUpdate']);
        $r->addRoute('POST', '/admin/item-shop/categories/{id:\d+}/delete', [AdminItemShopCategoriesController::class, 'categoriesDestroy']);
        $r->addRoute('GET', '/admin/item-shop/orders', [AdminItemShopOrdersController::class, 'ordersIndex']);
        $r->addRoute('GET', '/admin/item-shop', [AdminItemShopProductsController::class, 'productsIndex']);
        $r->addRoute('GET', '/admin/item-shop/new', [AdminItemShopProductsController::class, 'productsCreate']);
        $r->addRoute('POST', '/admin/item-shop', [AdminItemShopProductsController::class, 'productsStore']);
        $r->addRoute('GET', '/admin/item-shop/{id:\d+}', [AdminItemShopProductsController::class, 'productsEdit']);
        $r->addRoute('POST', '/admin/item-shop/{id:\d+}', [AdminItemShopProductsController::class, 'productsUpdate']);
        $r->addRoute('POST', '/admin/item-shop/{id:\d+}/delete', [AdminItemShopProductsController::class, 'productsDestroy']);
        $r->addRoute('POST', '/admin/item-shop/mass', [AdminItemShopProductsController::class, 'mass']);
        $r->addRoute('GET', '/admin/shops', [AdminShopsController::class, 'index']);
        $r->addRoute('GET', '/admin/shops/new', [AdminShopsController::class, 'create']);
        $r->addRoute('POST', '/admin/shops', [AdminShopsController::class, 'store']);
        $r->addRoute('GET', '/admin/shops/{id:\d+}', [AdminShopsController::class, 'edit']);
        $r->addRoute('POST', '/admin/shops/{id:\d+}', [AdminShopsController::class, 'update']);
        $r->addRoute('POST', '/admin/shops/{id:\d+}/delete', [AdminShopsController::class, 'destroy']);
        $r->addRoute('POST', '/admin/shops/{id:\d+}/items', [AdminShopsController::class, 'addItem']);
        $r->addRoute('POST', '/admin/shops/{id:\d+}/items/delete', [AdminShopsController::class, 'removeItem']);
        $r->addRoute('GET', '/admin/refine', [AdminRefineController::class, 'index']);
        $r->addRoute('GET', '/admin/refine/new', [AdminRefineController::class, 'create']);
        $r->addRoute('POST', '/admin/refine', [AdminRefineController::class, 'store']);
        $r->addRoute('GET', '/admin/refine/{id:\d+}', [AdminRefineController::class, 'edit']);
        $r->addRoute('POST', '/admin/refine/{id:\d+}', [AdminRefineController::class, 'update']);
        $r->addRoute('POST', '/admin/refine/{id:\d+}/delete', [AdminRefineController::class, 'destroy']);
        $r->addRoute('GET', '/admin/drops', [AdminDropsController::class, 'index']);
        $r->addRoute('GET', '/admin/drops/etc', [AdminDropsController::class, 'etc']);
        $r->addRoute('POST', '/admin/drops/etc', [AdminDropsController::class, 'saveEtc']);
        $r->addRoute('GET', '/admin/drops/common', [AdminDropsController::class, 'common']);
        $r->addRoute('POST', '/admin/drops/common', [AdminDropsController::class, 'saveCommon']);
        $r->addRoute('GET', '/admin/drops/mob/{id:\d+}', [AdminDropsController::class, 'mob']);
        $r->addRoute('POST', '/admin/drops/mob/{id:\d+}', [AdminDropsController::class, 'saveMob']);
        $r->addRoute('GET', '/admin/gms', [AdminGmsController::class, 'index']);
        $r->addRoute('GET', '/admin/gms/new', [AdminGmsController::class, 'create']);
        $r->addRoute('POST', '/admin/gms', [AdminGmsController::class, 'store']);
        $r->addRoute('GET', '/admin/gms/{id:\d+}', [AdminGmsController::class, 'edit']);
        $r->addRoute('POST', '/admin/gms/{id:\d+}', [AdminGmsController::class, 'update']);
        $r->addRoute('POST', '/admin/gms/{id:\d+}/delete', [AdminGmsController::class, 'destroy']);
        $r->addRoute('POST', '/admin/gms/hosts', [AdminGmsController::class, 'addHost']);
        $r->addRoute('POST', '/admin/gms/hosts/delete', [AdminGmsController::class, 'deleteHost']);
        $r->addRoute('POST', '/admin/gms/mass', [AdminGmsController::class, 'mass']);
        $r->addRoute('GET', '/admin/{kind:items|mobs}', [AdminGameProtoController::class, 'index']);
        $r->addRoute('POST', '/admin/{kind:items|mobs}/mass', [AdminGameProtoController::class, 'mass']);
        $r->addRoute('GET', '/admin/{kind:items|mobs}/new', [AdminGameProtoController::class, 'create']);
        $r->addRoute('POST', '/admin/{kind:items|mobs}', [AdminGameProtoController::class, 'store']);
        $r->addRoute('GET', '/admin/{kind:items|mobs}/{id:\d+}', [AdminGameProtoController::class, 'edit']);
        $r->addRoute('POST', '/admin/{kind:items|mobs}/{id:\d+}', [AdminGameProtoController::class, 'update']);
        $r->addRoute('POST', '/admin/{kind:items|mobs}/{id:\d+}/delete', [AdminGameProtoController::class, 'destroy']);
        $r->addRoute('GET', '/admin/logs/{table:[a-z0-9_]+}', [AdminLogsController::class, 'show']);
    }
}
