<?php

declare(strict_types=1);

namespace Mt2Cms\Http;

use Mt2Cms\Http\Controller\AccountController;
use Mt2Cms\Http\Controller\AdminAccountsController;
use Mt2Cms\Http\Controller\AdminAccountSecurityController;
use Mt2Cms\Http\Controller\AdminAdminsController;
use Mt2Cms\Http\Controller\AdminAuditLogController;
use Mt2Cms\Http\Controller\AdminAuthController;
use Mt2Cms\Http\Controller\AdminAwardsController;
use Mt2Cms\Http\Controller\AdminBansController;
use Mt2Cms\Http\Controller\AdminCashPackagesController;
use Mt2Cms\Http\Controller\AdminCommunityController;
use Mt2Cms\Http\Controller\AdminDownloadsController;
use Mt2Cms\Http\Controller\AdminPaymentsController;
use Mt2Cms\Http\Controller\AdminCharactersController;
use Mt2Cms\Http\Controller\AdminDashboardController;
use Mt2Cms\Http\Controller\AdminDropsController;
use Mt2Cms\Http\Controller\AdminGameProtoController;
use Mt2Cms\Http\Controller\AdminGmsController;
use Mt2Cms\Http\Controller\AdminGuildsController;
use Mt2Cms\Http\Controller\AdminItemShopCategoriesController;
use Mt2Cms\Http\Controller\AdminItemShopOrdersController;
use Mt2Cms\Http\Controller\AdminItemShopProductsController;
use Mt2Cms\Http\Controller\AdminLogsController;
use Mt2Cms\Http\Controller\AdminNewsCommentsController;
use Mt2Cms\Http\Controller\AdminNewsHubController;
use Mt2Cms\Http\Controller\AdminRolesController;
use Mt2Cms\Http\Controller\AdminNewsPostsController;
use Mt2Cms\Http\Controller\AdminNewsSettingsController;
use Mt2Cms\Http\Controller\AdminStoreHubController;
use Mt2Cms\Http\Controller\AdminRefineController;
use Mt2Cms\Http\Controller\AdminSettingsController;
use Mt2Cms\Http\Controller\AdminShopsController;
use Mt2Cms\Http\Controller\AdminTicketsController;
use Mt2Cms\Http\Controller\AuthController;
use Mt2Cms\Http\Controller\CaptchaController;
use Mt2Cms\Http\Controller\DonateController;
use Mt2Cms\Http\Controller\DownloadsController;
use Mt2Cms\Http\Controller\EmailVerificationController;
use Mt2Cms\Http\Controller\GameIconController;
use Mt2Cms\Http\Controller\HomeController;
use Mt2Cms\Http\Controller\ItemShopController;
use Mt2Cms\Http\Controller\LocaleController;
use Mt2Cms\Http\Controller\NewsController;
use Mt2Cms\Http\Controller\PasswordController;
use Mt2Cms\Http\Controller\PaymentWebhookController;
use Mt2Cms\Http\Controller\PlayerController;
use Mt2Cms\Http\Controller\RankingController;
use Mt2Cms\Http\Controller\StatusController;
use Mt2Cms\Http\Controller\SetupController;
use Mt2Cms\Http\Controller\TicketController;
use Mt2Cms\Setup\EnvWriter;

trait ControllerMap
{
private function resolveController(string $class): object
    {
        return match ($class) {
            HomeController::class => new HomeController(
                $this->theme,
                $this->auth,
                $this->csrf,
                $this->translator,
                $this->news,
                $this->players,
                $this->settings,
            ),
            NewsController::class => new NewsController(
                $this->theme,
                $this->auth,
                $this->csrf,
                $this->translator,
                $this->news,
                $this->newsComments,
                $this->settings,
            ),
            TicketController::class => new TicketController(
                $this->theme,
                $this->auth,
                $this->csrf,
                $this->translator,
                $this->tickets,
                $this->ticketUploads,
                $this->htmlSanitizer,
            ),
            AuthController::class => new AuthController(
                $this->theme,
                $this->auth,
                $this->csrf,
                $this->translator,
                $this->accounts,
                $this->settings,
                $this->accountEmailService,
                $this->banService,
                $this->mailer,
            ),
            AccountController::class => new AccountController(
                $this->theme,
                $this->auth,
                $this->csrf,
                $this->translator,
                $this->players,
                $this->accounts,
                $this->accountEmailService,
                $this->itemShopOrders,
                $this->payments,
                $this->mailer,
            ),
            PasswordController::class => new PasswordController(
                $this->theme,
                $this->auth,
                $this->csrf,
                $this->translator,
                $this->accountEmailService,
                $this->mailer,
                $this->settings,
            ),
            EmailVerificationController::class => new EmailVerificationController(
                $this->theme,
                $this->auth,
                $this->csrf,
                $this->translator,
                $this->accountEmailService,
                $this->mailer,
            ),
            StatusController::class => new StatusController(
                $this->theme,
                $this->auth,
                $this->csrf,
                $this->translator,
                $this->players,
                $this->serverChannels,
                $this->settings,
            ),
            DownloadsController::class => new DownloadsController(
                $this->theme,
                $this->auth,
                $this->csrf,
                $this->translator,
                $this->downloads,
                $this->downloadUploads,
            ),
            DonateController::class => new DonateController(
                $this->theme,
                $this->auth,
                $this->csrf,
                $this->translator,
                $this->cashPackages,
                $this->payments,
                $this->paymentCheckout,
                $this->cashCredits,
                $this->paypal,
                $this->accountEmailService,
                $this->settings,
            ),
            PaymentWebhookController::class => new PaymentWebhookController(
                $this->theme,
                $this->auth,
                $this->csrf,
                $this->translator,
                $this->paypal,
                $this->cashCredits,
            ),
            ItemShopController::class => new ItemShopController(
                $this->theme,
                $this->auth,
                $this->csrf,
                $this->translator,
                $this->itemShopCategories,
                $this->itemShopProducts,
                $this->itemShopPurchases,
                $this->itemTooltips,
                $this->settings,
                $this->accountEmailService,
            ),
            RankingController::class => new RankingController(
                $this->theme,
                $this->auth,
                $this->csrf,
                $this->translator,
                $this->players,
                $this->guilds,
            ),
            PlayerController::class => new PlayerController(
                $this->theme,
                $this->auth,
                $this->csrf,
                $this->translator,
                $this->players,
            ),
            GameIconController::class => new GameIconController(
                $this->theme,
                $this->auth,
                $this->csrf,
                $this->translator,
                $this->icons,
            ),
            LocaleController::class => new LocaleController(
                $this->theme,
                $this->auth,
                $this->csrf,
                $this->translator,
                $this->locales,
            ),
            CaptchaController::class => new CaptchaController(
                $this->theme,
                $this->auth,
                $this->csrf,
                $this->translator,
            ),
            SetupController::class => new SetupController(
                $this->theme,
                $this->auth,
                $this->csrf,
                $this->translator,
                $this->themeCatalog,
                new EnvWriter(),
            ),
            AdminAuthController::class => new AdminAuthController(
                $this->theme,
                $this->auth,
                $this->csrf,
                $this->translator,
                $this->adminAuth,
                $this->adminTheme,
                $this->acl,
                $this->settings,
                $this->adminTotp,
            ),
            AdminAccountSecurityController::class => new AdminAccountSecurityController(
                $this->theme,
                $this->auth,
                $this->csrf,
                $this->translator,
                $this->adminAuth,
                $this->adminTheme,
                $this->acl,
                $this->adminAudit,
                $this->adminTotp,
                $this->settings,
            ),
            AdminDashboardController::class => new AdminDashboardController(
                $this->theme,
                $this->auth,
                $this->csrf,
                $this->translator,
                $this->adminAuth,
                $this->adminTheme,
                $this->acl,
                $this->adminAudit,
                $this->players,
            ),
            AdminSettingsController::class => new AdminSettingsController(
                $this->theme,
                $this->auth,
                $this->csrf,
                $this->translator,
                $this->adminAuth,
                $this->adminTheme,
                $this->acl,
                $this->adminAudit,
                $this->settings,
                $this->themeCatalog,
                $this->locales,
            ),
            AdminAccountsController::class => new AdminAccountsController(
                $this->theme,
                $this->auth,
                $this->csrf,
                $this->translator,
                $this->adminAuth,
                $this->adminTheme,
                $this->acl,
                $this->adminAudit,
                $this->accounts,
                $this->players,
                $this->logs,
            ),
            AdminCharactersController::class => new AdminCharactersController(
                $this->theme,
                $this->auth,
                $this->csrf,
                $this->translator,
                $this->adminAuth,
                $this->adminTheme,
                $this->acl,
                $this->adminAudit,
                $this->players,
                $this->items,
                $this->guilds,
                $this->logs,
                $this->accounts,
            ),
            AdminGameProtoController::class => new AdminGameProtoController(
                $this->theme,
                $this->auth,
                $this->csrf,
                $this->translator,
                $this->adminAuth,
                $this->adminTheme,
                $this->acl,
                $this->adminAudit,
                $this->gameProto,
                $this->protoFields,
                $this->mobDrops,
                $this->protoEnums,
            ),
            AdminLogsController::class => new AdminLogsController(
                $this->theme,
                $this->auth,
                $this->csrf,
                $this->translator,
                $this->adminAuth,
                $this->adminTheme,
                $this->acl,
                $this->adminAudit,
                $this->logs,
            ),
            AdminGuildsController::class => new AdminGuildsController(
                $this->theme,
                $this->auth,
                $this->csrf,
                $this->translator,
                $this->adminAuth,
                $this->adminTheme,
                $this->acl,
                $this->adminAudit,
                $this->guilds,
            ),
            AdminGmsController::class => new AdminGmsController(
                $this->theme,
                $this->auth,
                $this->csrf,
                $this->translator,
                $this->adminAuth,
                $this->adminTheme,
                $this->acl,
                $this->adminAudit,
                $this->common,
                $this->accounts,
            ),
            AdminAwardsController::class => new AdminAwardsController(
                $this->theme,
                $this->auth,
                $this->csrf,
                $this->translator,
                $this->adminAuth,
                $this->adminTheme,
                $this->acl,
                $this->adminAudit,
                $this->awards,
                $this->accounts,
                $this->players,
                $this->gameProto,
            ),
            AdminNewsHubController::class => new AdminNewsHubController(
                $this->theme,
                $this->auth,
                $this->csrf,
                $this->translator,
                $this->adminAuth,
                $this->adminTheme,
                $this->acl,
                $this->adminAudit,
                $this->news,
                $this->newsComments,
                $this->settings,
                $this->htmlSanitizer,
                $this->newsUploads,
            ),
            AdminStoreHubController::class => new AdminStoreHubController(
                $this->theme,
                $this->auth,
                $this->csrf,
                $this->translator,
                $this->adminAuth,
                $this->adminTheme,
                $this->acl,
                $this->adminAudit,
                $this->itemShopCategories,
                $this->itemShopProducts,
                $this->itemShopOrders,
                $this->gameProto,
            ),
            AdminNewsPostsController::class => new AdminNewsPostsController(
                $this->theme,
                $this->auth,
                $this->csrf,
                $this->translator,
                $this->adminAuth,
                $this->adminTheme,
                $this->acl,
                $this->adminAudit,
                $this->news,
                $this->newsComments,
                $this->settings,
                $this->htmlSanitizer,
                $this->newsUploads,
            ),
            AdminNewsCommentsController::class => new AdminNewsCommentsController(
                $this->theme,
                $this->auth,
                $this->csrf,
                $this->translator,
                $this->adminAuth,
                $this->adminTheme,
                $this->acl,
                $this->adminAudit,
                $this->news,
                $this->newsComments,
                $this->settings,
                $this->htmlSanitizer,
                $this->newsUploads,
            ),
            AdminNewsSettingsController::class => new AdminNewsSettingsController(
                $this->theme,
                $this->auth,
                $this->csrf,
                $this->translator,
                $this->adminAuth,
                $this->adminTheme,
                $this->acl,
                $this->adminAudit,
                $this->news,
                $this->newsComments,
                $this->settings,
                $this->htmlSanitizer,
                $this->newsUploads,
            ),
            AdminTicketsController::class => new AdminTicketsController(
                $this->theme,
                $this->auth,
                $this->csrf,
                $this->translator,
                $this->adminAuth,
                $this->adminTheme,
                $this->acl,
                $this->adminAudit,
                $this->tickets,
                $this->ticketUploads,
                $this->htmlSanitizer,
            ),
            AdminItemShopProductsController::class => new AdminItemShopProductsController(
                $this->theme,
                $this->auth,
                $this->csrf,
                $this->translator,
                $this->adminAuth,
                $this->adminTheme,
                $this->acl,
                $this->adminAudit,
                $this->itemShopCategories,
                $this->itemShopProducts,
                $this->itemShopOrders,
                $this->gameProto,
            ),
            AdminItemShopCategoriesController::class => new AdminItemShopCategoriesController(
                $this->theme,
                $this->auth,
                $this->csrf,
                $this->translator,
                $this->adminAuth,
                $this->adminTheme,
                $this->acl,
                $this->adminAudit,
                $this->itemShopCategories,
                $this->itemShopProducts,
                $this->itemShopOrders,
                $this->gameProto,
            ),
            AdminItemShopOrdersController::class => new AdminItemShopOrdersController(
                $this->theme,
                $this->auth,
                $this->csrf,
                $this->translator,
                $this->adminAuth,
                $this->adminTheme,
                $this->acl,
                $this->adminAudit,
                $this->itemShopCategories,
                $this->itemShopProducts,
                $this->itemShopOrders,
                $this->gameProto,
            ),
            AdminShopsController::class => new AdminShopsController(
                $this->theme,
                $this->auth,
                $this->csrf,
                $this->translator,
                $this->adminAuth,
                $this->adminTheme,
                $this->acl,
                $this->adminAudit,
                $this->shops,
                $this->gameProto,
            ),
            AdminRefineController::class => new AdminRefineController(
                $this->theme,
                $this->auth,
                $this->csrf,
                $this->translator,
                $this->adminAuth,
                $this->adminTheme,
                $this->acl,
                $this->adminAudit,
                $this->refine,
                $this->gameProto,
            ),
            AdminDropsController::class => new AdminDropsController(
                $this->theme,
                $this->auth,
                $this->csrf,
                $this->translator,
                $this->adminAuth,
                $this->adminTheme,
                $this->acl,
                $this->adminAudit,
                $this->dropFiles,
                $this->mobDrops,
                $this->gameProto,
                $this->gameProfile,
            ),
            AdminAdminsController::class => new AdminAdminsController(
                $this->theme,
                $this->auth,
                $this->csrf,
                $this->translator,
                $this->adminAuth,
                $this->adminTheme,
                $this->acl,
                $this->adminAudit,
                new \Mt2Cms\Repository\AdminRepository($this->cmsDb, $this->adminRoles),
                $this->adminRoles,
                $this->adminTotp,
            ),
            AdminRolesController::class => new AdminRolesController(
                $this->theme,
                $this->auth,
                $this->csrf,
                $this->translator,
                $this->adminAuth,
                $this->adminTheme,
                $this->acl,
                $this->adminAudit,
                $this->adminRoles,
            ),
            AdminAuditLogController::class => new AdminAuditLogController(
                $this->theme,
                $this->auth,
                $this->csrf,
                $this->translator,
                $this->adminAuth,
                $this->adminTheme,
                $this->acl,
                $this->adminAudit,
                new \Mt2Cms\Repository\AdminAuditRepository($this->cmsDb),
            ),
            AdminBansController::class => new AdminBansController(
                $this->theme,
                $this->auth,
                $this->csrf,
                $this->translator,
                $this->adminAuth,
                $this->adminTheme,
                $this->acl,
                $this->adminAudit,
                $this->banRepo,
                $this->banService,
                $this->accounts,
            ),
            AdminDownloadsController::class => new AdminDownloadsController(
                $this->theme,
                $this->auth,
                $this->csrf,
                $this->translator,
                $this->adminAuth,
                $this->adminTheme,
                $this->acl,
                $this->adminAudit,
                $this->downloads,
                $this->downloadUploads,
            ),
            AdminCommunityController::class => new AdminCommunityController(
                $this->theme,
                $this->auth,
                $this->csrf,
                $this->translator,
                $this->adminAuth,
                $this->adminTheme,
                $this->acl,
                $this->adminAudit,
                $this->serverChannels,
                $this->settings,
            ),
            AdminCashPackagesController::class => new AdminCashPackagesController(
                $this->theme,
                $this->auth,
                $this->csrf,
                $this->translator,
                $this->adminAuth,
                $this->adminTheme,
                $this->acl,
                $this->adminAudit,
                $this->cashPackages,
                $this->settings,
            ),
            AdminPaymentsController::class => new AdminPaymentsController(
                $this->theme,
                $this->auth,
                $this->csrf,
                $this->translator,
                $this->adminAuth,
                $this->adminTheme,
                $this->acl,
                $this->adminAudit,
                $this->payments,
                $this->cashCredits,
            ),
            default => throw new \RuntimeException('Unknown controller: ' . $class),
        };
    }
}
